<?php
if (!defined('ABSPATH')) {
    exit;
}

trait TCARM_Admin_Page_Download_Files_Trait {
    private function render_download_files_settings_card($settings) {
        $files = isset($settings['download_files']) && is_array($settings['download_files']) ? $settings['download_files'] : array();
        uasort($files, function($a, $b) { return ((int) ($a['sort_order'] ?? 999)) <=> ((int) ($b['sort_order'] ?? 999)); });
        ob_start();
        ?>
        <div class="tcarm-panel tcarm-card-panel tcarm-settings-card tcarm-admin-card tcarm-download-settings">
            <div class="tcarm-panel-header"><h2><?php echo esc_html__('Download File Settings', 'shinseiflow-application-review'); ?></h2><p><?php echo esc_html__('Configure files that approved applicants can download from the application status page.', 'shinseiflow-application-review'); ?></p></div>
            <div class="tcarm-settings-card-body">
                <p class="description"><?php echo esc_html__('Display names and descriptions are shown in the frontend download area. File URLs are not shown directly on the frontend and are served only after the download process validates them.', 'shinseiflow-application-review'); ?></p>
                <div class="tcarm-download-settings-list" data-tcarm-download-list>
                    <?php if (empty($files)): ?>
                        <?php
                        // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Download file row markup escapes names, URLs, textarea content, and attributes before output.
                        echo $this->render_download_file_setting_row('new_' . time(), array('label' => '', 'description' => '', 'attachment_id' => 0, 'file_url' => '', 'enabled' => '1', 'sort_order' => 10));
                        ?>
                    <?php else: ?>
                        <?php foreach ($files as $key => $file): ?>
                            <?php
                            // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Download file row markup escapes names, URLs, textarea content, and attributes before output.
                            echo $this->render_download_file_setting_row($key, $file);
                            ?>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
                <button type="button" class="button tcarm-download-add-row" data-tcarm-add-download-file><?php echo esc_html__('+ Add File', 'shinseiflow-application-review'); ?></button>
                <script type="text/template" id="tcarm-download-file-template">
                    <?php
                    // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Template markup is generated by escaped row renderer and only escapes the closing script sequence.
                    echo str_replace('</script>', '<\/script>', $this->render_download_file_setting_row('__KEY__', array('label' => '', 'description' => '', 'attachment_id' => 0, 'file_url' => '', 'enabled' => '1', 'sort_order' => 999)));
                    ?>
                </script>
            </div>
        </div>
        <?php
        return ob_get_clean();
    }

    private function render_download_file_setting_row($key, $file) {
        $file = wp_parse_args(is_array($file) ? $file : array(), array(
            'label' => '',
            'description' => '',
            'attachment_id' => 0,
            'file_url' => '',
            'enabled' => '1',
            'sort_order' => 10,
        ));
        $key = sanitize_key($key);
        $name = self::OPTION_SETTINGS . '[download_files][' . $key . ']';
        ob_start();
        ?>
        <div class="tcarm-download-file-row tcarm-download-settings-item" data-tcarm-download-row>
            <input type="hidden" class="tcarm-download-delete" name="<?php echo esc_attr($name); ?>[_delete]" value="0">
            <button type="button" class="tcarm-icon-button tcarm-delete-download-file" data-tcarm-remove-download-file title="<?php echo esc_attr__('Delete file setting', 'shinseiflow-application-review'); ?>" aria-label="<?php echo esc_attr__('Delete file setting', 'shinseiflow-application-review'); ?>"><?php echo wp_kses($this->admin_icon_svg('delete'), $this->admin_icon_svg_allowed_tags()); ?></button>
            <div class="tcarm-download-file-grid">
                <label><?php echo esc_html__('Display Name', 'shinseiflow-application-review'); ?></label>
                <input type="text" name="<?php echo esc_attr($name); ?>[label]" value="<?php echo esc_attr($file['label']); ?>" placeholder="<?php echo esc_attr__('Example: Document (Color)', 'shinseiflow-application-review'); ?>">
                <label><?php echo esc_html__('Description', 'shinseiflow-application-review'); ?></label>
                <textarea name="<?php echo esc_attr($name); ?>[description]" rows="3" placeholder="<?php echo esc_attr__('Example: A document that can be used for printed materials, websites, and related purposes.', 'shinseiflow-application-review'); ?>"><?php echo esc_textarea($file['description']); ?></textarea>
                <label><?php echo esc_html__('File', 'shinseiflow-application-review'); ?></label>
                <div>
                    <input type="hidden" class="tcarm-download-attachment-id" name="<?php echo esc_attr($name); ?>[attachment_id]" value="<?php echo esc_attr(absint($file['attachment_id'])); ?>">
                    <input type="url" class="tcarm-download-file-url" name="<?php echo esc_attr($name); ?>[file_url]" value="<?php echo esc_url($file['file_url']); ?>" placeholder="<?php echo esc_attr__('Select media or enter a file URL', 'shinseiflow-application-review'); ?>">
                    <div class="tcarm-download-file-actions">
                        <button type="button" class="button" data-tcarm-select-download-file><?php echo esc_html__('Select from Media Library', 'shinseiflow-application-review'); ?></button>
                        <button type="button" class="button" data-tcarm-clear-download-file><?php echo esc_html__('Clear', 'shinseiflow-application-review'); ?></button>
                    </div>
                    <div class="tcarm-download-file-meta"><?php echo esc_html__('When selected from the media library, the attachment ID is retained. Attachment ID:', 'shinseiflow-application-review'); ?><span data-tcarm-attachment-label><?php echo esc_html(absint($file['attachment_id']) ?: '-'); ?></span></div>
                </div>
                <label><?php echo esc_html__('Enabled', 'shinseiflow-application-review'); ?></label>
                <label class="tcarm-download-file-enabled"><input type="checkbox" name="<?php echo esc_attr($name); ?>[enabled]" value="1" <?php checked($file['enabled'], '1'); ?>> <?php echo esc_html__('Show on the frontend', 'shinseiflow-application-review'); ?></label>
                <label><?php echo esc_html__('Sort Order', 'shinseiflow-application-review'); ?></label>
                <input type="number" class="small-text tcarm-download-sort" name="<?php echo esc_attr($name); ?>[sort_order]" value="<?php echo esc_attr(absint($file['sort_order'])); ?>" min="0" step="1">
            </div>
        </div>
        <?php
        return ob_get_clean();
    }

    public function render_download_files_settings_page() {
        $settings = self::get_settings();
        $this->open_admin_wrap(__('Download File Settings', 'shinseiflow-application-review'));
        ?>
            <form method="post" action="options.php" class="tcarm-basic-settings-form tcarm-download-files-settings-form tcarm-admin-download-files-page tcarm-admin-settings-page">
                <?php settings_fields('tcarm_settings_group'); ?>
                <input type="hidden" name="<?php echo esc_attr(self::OPTION_SETTINGS); ?>[_partial]" value="1">

                <?php
                // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Download settings card markup escapes dynamic row values before output.
                echo $this->render_download_files_settings_card($settings);
                ?>

                <?php submit_button(__('Save Settings', 'shinseiflow-application-review')); ?>
            </form>
        </div>
        <?php
    }
}
